[Ethereum]
# 以太坊RPC节点URL，可以使用任何RPC节点
# 示例：
# Infura: https://sepolia.infura.io/v3/YOUR_API_KEY
# Alchemy: https://eth-sepolia.alchemyapi.io/v2/YOUR_API_KEY
# Public RPC: https://rpc.sepolia.dev
# 本地节点: http://localhost:8545
# Monad主网RPC: https://rpc.monad.xyz
# Monad测试网RPC: https://rpc.testnet.monad.xyz
#   https://testnet-rpc.monad.xyz
rpc_url = https://testnet-rpc.monad.xyz

# 智能合约地址
contract_address = 0x00***************************50

# 用于签名交易的私钥（确保该地址是合约的所有者）
private_key = 63**************************************************a1a

[VolcEngine]
# 火山引擎API密钥
api_key = 2b***********************5d

[Pinata]
# Pinata API密钥（需要注册Pinata账号获取）
# 注册地址：https://app.pinata.cloud/register
api_key = a*********************************1
api_secret = b6************************************************9